app/Http/routes.php
     Route::get('password/email/{one?}/{two?}/{three?}/{four?}/{five?}',['as' => 'password.email', 'uses' => 'Auth\PasswordController@getEmail']);
        Breadcrumbs::register('password.email', function ($breadcrumbs) {
            $breadcrumbs->parent('/');
            $breadcrumbs->push('Login', url('auth/login'));
            $breadcrumbs->push('Forgot Password', url('password/email'));
        });

   
    // register page
        Route::get('auth/register/{one?}/{two?}/{three?}/{four?}/{five?}',['as' => 'auth.register', 'uses' => 'Auth\AuthController@getRegister']);
        Breadcrumbs::register('auth.register', function ($breadcrumbs) {
            $breadcrumbs->parent('/');
            $breadcrumbs->push('Login', url('auth/login'));
            $breadcrumbs->push('Create Account', url('auth/register'));
        });


  // Auth login
        Route::get('auth/login/{one?}/{two?}/{three?}/{four?}/{five?}',['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
        Breadcrumbs::register('auth.login', function ($breadcrumbs) {
            $breadcrumbs->parent('/');
               $breadcrumbs->push('Create Account', url('auth/register'));
            $breadcrumbs->push('Login', url('auth/login'));
         
        });












    
    Route::get('account/activate/{token}', ['as' => 'account.activate', 'uses' => 'Auth\AuthController@accountActivate']);
    Route::get('getmail/{token}', 'Auth\AuthController@getMail');
    Route::get('verify-otp', ['as' => 'otp-verification', 'uses' => 'Auth\AuthController@getVerifyOTP']);
    Route::post('verify-otp', ['as' => 'otp-verification', 'uses' => 'Auth\AuthController@verifyOTP']);
    Route::post('resend/opt', ['as' => 'resend-otp', 'uses' => 'Auth\AuthController@resendOTP']);

    /*
      |-------------------------------------------------------------------------------
      | Admin Routes
      |-------------------------------------------------------------------------------
      | Here is defining entire routes for the Admin Panel
      |
     */
    Route::group(['middleware' => 'roles', 'middleware' => 'auth', 'middleware' => 'install', 'middleware' => 'update'], function () {
        //Notification marking
        Route::post('mark-read/{id}', 'Common\NotificationController@markRead');
        Route::post('mark-all-read/{id}', 'Common\NotificationController@markAllRead');
        
        Route::get('notifications-list', ['as' => 'notification.list', 'uses' => 'Common\NotificationController@show']);
        Route::post('notification-delete/{id}', ['as' => 'notification.delete', 'uses' => 'Common\NotificationController@delete']);
        Route::get('notifications-list/delete', ['as' => 'notification.delete.all', 'uses' => 'Common\NotificationController@deleteAll']);

        Route::get('settings-notification', ['as' => 'notification.settings', 'uses' => 'Admin\helpdesk\SettingsController@notificationSettings']);
        Route::get('delete-read-notification', 'Admin\helpdesk\SettingsController@deleteReadNoti');
        Route::post('delete-notification-log', 'Admin\helpdesk\SettingsController@deleteNotificationLog');
        // resource is a function to process create,edit,read and delete
        Route::resource('groups', 'Admin\helpdesk\GroupController'); // for group module, for CRUD
        
        Route::resource('departments', 'Admin\helpdesk\DepartmentController'); // for departments module, for CRUD
        
        Route::resource('teams', 'Admin\helpdesk\TeamController'); // in teams module, for CRUD
        Route::get('/assign-teams/{id}', ['as' => 'teams.profile.show', 'uses' => 'Admin\helpdesk\TeamController@TeamShow']);
        Route::get('/teams/show/{id}', ['as' => 'teams.show', 'uses' => 'Admin\helpdesk\TeamController@show']); /*  Get Team View */
         Breadcrumbs::register('teams.show', function ($breadcrumbs) {
            $breadcrumbs->parent('teams.index');
            $breadcrumbs->push(Lang::get('lang.show'), url('teams/{teams}/show'));
        });
Route::get('getshow/{id}', ['as' => 'teams.getshow.list', 'uses' => 'Admin\helpdesk\TeamController@getshow']);
        Route::resource('agents', 'Admin\helpdesk\AgentController'); // in agents module, for CRUD
        
        Route::resource('emails', 'Admin\helpdesk\EmailsController'); // in emails module, for CRUD
        
        Route::resource('banlist', 'Admin\helpdesk\BanlistController'); // in banlist module, for CRUD
        
        Route::get('banlist/delete/{id}', ['as' => 'banlist.delete', 'uses' => 'Admin\helpdesk\BanlistController@delete']); // in banlist module, for CRUD
        /*
         * Templates
         */
        
        Route::resource('templates', 'Common\TemplateController');
        Route::get('get-templates', 'Common\TemplateController@GetTemplates');
        Route::get('templates-delete', 'Common\TemplateController@destroy');
        Route::get('testmail/{id}', 'Common\TemplateController@mailtest');
        Route::resource('template-sets', 'Common\TemplateSetController'); // in template module, for CRUD
        Route::get('delete-sets/{id}', ['as' => 'sets.delete', 'uses' => 'Common\TemplateSetController@deleteSet']);
        Route::get('show-template/{id}', ['as' => 'show.templates', 'uses' => 'Common\TemplateController@showTemplate']);
        Route::get('activate-templateset/{name}', ['as' => 'active.template-set', 'uses' => 'Common\TemplateSetController@activateSet']);
        Route::resource('template', 'Admin\helpdesk\TemplateController'); // in template module, for CRUD
        Route::get('list-directories', 'Admin\helpdesk\TemplateController@listdirectories');
        Route::get('activate-set/{dir}', ['as' => 'active.set', 'uses' => 'Admin\helpdesk\TemplateController@activateset']);
        Route::get('list-templates/{template}/{directory}', ['as' => 'template.list', 'uses' => 'Admin\helpdesk\TemplateController@listtemplates']);
        Route::get('read-templates/{template}/{directory}', ['as' => 'template.read', 'uses' => 'Admin\helpdesk\TemplateController@readtemplate']);
        Route::patch('write-templates/{contents}/{directory}', ['as' => 'template.write', 'uses' => 'Admin\helpdesk\TemplateController@writetemplate']);
        Route::post('create-templates', ['as' => 'template.createnew', 'uses' => 'Admin\helpdesk\TemplateController@createtemplate']);
        Route::get('delete-template/{template}/{path}', ['as' => 'templates.delete', 'uses' => 'Admin\helpdesk\TemplateController@deletetemplate']);
        Route::get('getdiagno', ['as' => 'getdiagno', 'uses' => 'Admin\helpdesk\TemplateController@formDiagno']); // for getting form for diagnostic
        
        Route::post('postdiagno', ['as' => 'postdiagno', 'uses' => 'Admin\helpdesk\TemplateController@postDiagno']); // for getting form for diagnostic
        Route::resource('helptopic', 'Admin\helpdesk\HelptopicController'); // in helptopics module, for CRUD
        
       Route::resource('sla', 'SLA\SlaController'); // in SLA Plan module, for CRUD

        Route::get('sla/plan/getindex', ['as' => 'sla.plan.getindex', 'uses' => 'SLA\SlaController@getIndex']);
//        Breadcrumbs::register('sla.create', function ($breadcrumbs) {
//            $breadcrumbs->parent('sla.index');
//            $breadcrumbs->push(Lang::get('lang.create'), route('sla.create'));
//        });
//        Breadcrumbs::register('sla.edit', function ($breadcrumbs) {
//            $breadcrumbs->parent('sla.index');
//            $breadcrumbs->push(Lang::get('lang.edit'), url('sla/{sla}/edit'));
//        });
        Route::get('sla_plan/autofill', ['as' => 'post.sla_plan.autofill', 'uses' => 'SLA\SlaController@autofill']);
        Route::get('sla_plan/delete/{id}', ['as' => 'sla.plan.delete', 'uses' => 'SLA\SlaController@destroy']);


        Route::resource('forms', 'Admin\helpdesk\FormController');
        Route::get('forms/add-child/{formid}', ['as' => 'forms.add.child', 'uses' => 'Admin\helpdesk\FormController@addChildForm']);
        Route::post('forms/field/{fieldid}/child', [
            'as' => 'forms.field.child',
            'uses' => 'Admin\helpdesk\FormController@addChild',
        ]);
        Route::get('forms/render/child', [
            'as' => 'forms.field.child',
            'uses' => 'Admin\helpdesk\FormController@renderChild',
        ]);
        
        Route::get('delete-forms/{id}', ['as' => 'forms.delete', 'uses' => 'Admin\helpdesk\FormController@delete']);
        //$router->model('id','getcompany');
        Route::get('job-scheduler', ['as' => 'get.job.scheder', 'uses' => 'Admin\helpdesk\SettingsController@getSchedular']); //to get ob scheduler form page
        
        Route::patch('post-scheduler', ['as' => 'post.job.scheduler', 'uses' => 'Admin\helpdesk\SettingsController@postSchedular']); //to update job scheduler
        Route::get('agent-profile-page/{id}', ['as' => 'agent.profile.page', 'uses' => 'Admin\helpdesk\AgentController@agent_profile']);
        Route::get('getcompany', ['as' => 'getcompany', 'uses' => 'Admin\helpdesk\SettingsController@getcompany']); // direct to company setting page
        
        Route::patch('postcompany/{id}', 'Admin\helpdesk\SettingsController@postcompany'); // Updating the Company table with requests
        Route::get('delete-logo', ['as' => 'delete.logo', 'uses' => 'Admin\helpdesk\SettingsController@deleteLogo']); // deleting a logo
        Route::get('getsystem', ['as' => 'getsystem', 'uses' => 'Admin\helpdesk\SettingsController@getsystem']); // direct to system setting page
        
        Route::patch('postsystem/{id}', 'Admin\helpdesk\SettingsController@postsystem'); // Updating the System table with requests
        Route::get('getticket', ['as' => 'getticket', 'uses' => 'Admin\helpdesk\SettingsController@getticket']); // direct to ticket setting page
        
        Route::patch('postticket/{id}', 'Admin\helpdesk\SettingsController@postticket'); // Updating the Ticket table with requests

routes/web.php
		Route::group(['middleware' => ['limit.exceeded']], function () {
        
        Route::group(['middleware' => 'update', 'middleware' => 'install'], function () {
            Auth::routes();
            Route::post('login', ['uses' => 'Auth\AuthController@postLogin', 'as' => 'post.login']);
            Route::get('auth/logout', ['uses' => 'Auth\AuthController@getLogout', 'as' => 'get.logout']);
            Route::post('auth/register', ['uses' => 'Auth\AuthController@postRegister', 'as' => 'post.register']);

            Route::get('social/login/redirect/{provider}/{redirect?}', ['uses' => 'Auth\AuthController@redirectToProvider', 'as' => 'social.login']);
            Route::get('social/login/{provider}', ['as' => 'social.login.callback', 'uses' => 'Auth\AuthController@handleProviderCallback']);
            Route::get('social-sync', ['as' => 'social.sync', 'uses' => 'Client\helpdesk\GuestController@sync']);
        });
        
        Route::get('date/get',function(){
            return faveoDate("",\Input::get('format'),\Input::get('tz'));
        });

        /*
          |-------------------------------------------------------------------------------
          | @Anjali
          |-------------------------------------------------------------------------------
          | Here is defining entire routes for the Admin Panel
          |
         */
        Route::get('password/email/{one?}/{two?}/{three?}/{four?}/{five?}', ['as' => 'password.email', 'uses' => 'Auth\PasswordController@getEmail']);
        

        // register page
        Route::get('auth/register/{one?}/{two?}/{three?}/{four?}/{five?}', ['as' => 'auth.register', 'uses' => 'Auth\AuthController@getRegister']);
        
        Route::get('login', function () {
            return redirect()->route('auth.login');
        });

        // Auth login
        Route::get('auth/login/{one?}/{two?}/{three?}/{four?}/{five?}', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
        


        Route::get('account/activate/{token}', ['as' => 'account.activate', 'uses' => 'Auth\AuthController@accountActivate']);
        Route::get('getmail/{token}', 'Auth\AuthController@getMail');
        Route::get('verify-otp', ['as' => 'otp-verification', 'uses' => 'Auth\AuthController@getVerifyOTP']);
        Route::post('verify-otp', ['as' => 'otp-verification', 'uses' => 'Auth\AuthController@verifyOTP']);
        Route::post('resend/otp', ['as' => 'resend-otp', 'uses' => 'Auth\AuthController@resendOTP']);

        /*
          |-------------------------------------------------------------------------------
          | Admin Routes
          |-------------------------------------------------------------------------------
          | Here is defining entire routes for the Admin Panel
          |
         */
        Route::group(['middleware' => 'roles', 'middleware' => 'auth', 'middleware' => 'install', 'middleware' => 'update'], function () {
            //Notification marking
            Route::post('mark-read/{id}', 'Common\NotificationController@markRead');
            Route::post('mark-all-read/{id}', 'Common\NotificationController@markAllRead');
            
            /**
             * Notification api
             */
            
            Route::get('notification/api/{userid}',[
                'as'=>'notification.api',
                'uses'=>'Agent\helpdesk\Notifications\Notification@appNotification'
            ])->middleware(['role.agent']);
            
            Route::get('notification/api/seen/{userid}',[
                'as'=>'notification.api.seen',
                'uses'=>'Agent\helpdesk\Notifications\Notification@notificationSeen'
            ])->middleware(['role.agent']);
            
            Route::get('notification/api/unseen/count/{userid}',[
                'as'=>'notification.api.unseen.count',
                'uses'=>'Agent\helpdesk\Notifications\Notification@notificationUnSeenCount'
            ])->middleware(['role.agent']);
            
            Route::get('notification/api/seen/all/{userid}',[
                'as'=>'notification.api.seen.all',
                'uses'=>'Agent\helpdesk\Notifications\Notification@notificationUpdateSeenAll'
            ])->middleware(['role.agent']);

            Route::get('notifications-list', ['as' => 'notification.list', 'uses' => 'Common\NotificationController@show']);
            Route::post('notification-delete/{id}', ['as' => 'notification.delete', 'uses' => 'Common\NotificationController@delete']);
            Route::get('notifications-list/delete', ['as' => 'notification.delete.all', 'uses' => 'Common\NotificationController@deleteAll']);

            Route::get('settings-notification', ['as' => 'notification.settings', 'uses' => 'Admin\helpdesk\SettingsController@notificationSettings']);
            Route::get('delete-read-notification', 'Admin\helpdesk\SettingsController@deleteReadNoti');
            Route::post('delete-notification-log', 'Admin\helpdesk\SettingsController@deleteNotificationLog');
            // resource is a function to process create,edit,read and delete
            Route::resource('groups', 'Admin\helpdesk\GroupController'); // for group module, for CRUD

            Route::resource('departments', 'Admin\helpdesk\DepartmentController'); // for departments module, for CRUD
            Route::get('departments-table-data', ['as' => 'get-department-table-data', 'uses' => 'Admin\helpdesk\DepartmentController@getDepartmentTable']);

            Route::get('/department/{id}',['as' =>'department.profile.show','uses'=>'Admin\helpdesk\DepartmentController@DepartmentShow']);
            Route::get('/department/userprofile/{id}',['as' =>'department.userprofile.show','uses'=>'Admin\helpdesk\DepartmentController@DepartmentUserprofile']);
            
            Route::resource('teams', 'Admin\helpdesk\TeamController'); // in teams module, for CRUD
            Route::get('team-table-data', ['as' => 'get-team-table-data', 'uses' => 'Admin\helpdesk\TeamController@getTeamTable']);

            Route::get('/assign-teams/{id}', ['as' => 'teams.profile.show', 'uses' => 'Admin\helpdesk\TeamController@TeamShow']);
            Route::get('/teams/show/{id}', ['as' => 'teams.show', 'uses' => 'Admin\helpdesk\TeamController@show']); /*  Get Team View */
            
            Route::get('getshow/{id}', ['as' => 'teams.getshow.list', 'uses' => 'Admin\helpdesk\TeamController@getshow']);
            Route::resource('agents', 'Admin\helpdesk\AgentController'); // in agents module, for CRUD

            Route::resource('emails', 'Admin\helpdesk\EmailsController'); // in emails module, for CRUD

            Route::resource('banlist', 'Admin\helpdesk\BanlistController'); // in banlist module, for CRUD

            Route::post('banlist/delete/{id}', ['as' => 'banlist.delete', 'uses' => 'Admin\helpdesk\BanlistController@delete']); // in banlist module, for CRUD
            /*
             * Templates
             */

            Route::resource('templates', 'Common\TemplateController');
            Route::get('get-templates', 'Common\TemplateController@GetTemplates');
            Route::get('templates-delete', 'Common\TemplateController@destroy');
            Route::get('testmail/{id}', 'Common\TemplateController@mailtest');
            Route::resource('template-sets', 'Common\TemplateSetController'); // in template module, for CRUD
            Route::get('delete-sets/{id}', ['as' => 'sets.delete', 'uses' => 'Common\TemplateSetController@deleteSet']);
            Route::get('get-faveo-template-table-data/{id}', ['as' => 'template-table-data', 'uses' => 'Common\TemplateController@getTemplateTableData']);
            Route::get('show-template/{id}', ['as' => 'show.templates', 'uses' => 'Common\TemplateController@showTemplate']);
            Route::get('activate-templateset/{name}', ['as' => 'active.template-set', 'uses' => 'Common\TemplateSetController@activateSet']);
            Route::resource('template', 'Admin\helpdesk\TemplateController'); // in template module, for CRUD
            Route::get('list-directories', 'Admin\helpdesk\TemplateController@listdirectories');
            Route::get('activate-set/{dir}', ['as' => 'active.set', 'uses' => 'Admin\helpdesk\TemplateController@activateset']);
            Route::get('list-templates/{template}/{directory}', ['as' => 'template.list', 'uses' => 'Admin\helpdesk\TemplateController@listtemplates']);
            Route::get('read-templates/{template}/{directory}', ['as' => 'template.read', 'uses' => 'Admin\helpdesk\TemplateController@readtemplate']);
            Route::patch('write-templates/{contents}/{directory}', ['as' => 'template.write', 'uses' => 'Admin\helpdesk\TemplateController@writetemplate']);
            Route::post('create-templates', ['as' => 'template.createnew', 'uses' => 'Admin\helpdesk\TemplateController@createtemplate']);
            Route::get('delete-template/{template}/{path}', ['as' => 'templates.delete', 'uses' => 'Admin\helpdesk\TemplateController@deletetemplate']);
            Route::get('getdiagno', ['as' => 'getdiagno', 'uses' => 'Admin\helpdesk\TemplateController@formDiagno']); // for getting form for diagnostic

            Route::post('postdiagno', ['as' => 'postdiagno', 'uses' => 'Admin\helpdesk\TemplateController@postDiagno']); // for getting form for diagnostic
            Route::resource('helptopic', 'Admin\helpdesk\HelptopicController'); // in helptopics module, for CRUD

            Route::resource('sla', 'SLA\SlaController'); // in SLA Plan module, for CRUD

            Route::get('sla/plan/getindex', ['as' => 'sla.plan.getindex', 'uses' => 'SLA\SlaController@getIndex']);
//        Breadcrumbs::register('sla.create', function ($breadcrumbs) {
//            $breadcrumbs->parent('sla.index');
//            $breadcrumbs->push(Lang::get('lang.create'), route('sla.create'));
//        });
//        Breadcrumbs::register('sla.edit', function ($breadcrumbs) {

resources/views/themes/default1/admin/helpdesk/agent/departments/create.blade.php
@extends('themes.default1.admin.layout.admin')

@section('Staffs')
active
@stop

@section('staffs-bar')
active
@stop

@section('departments')
class="active"
@stop


@section('HeadInclude')
@stop
<!-- header -->
@section('PageHeader')
<h1>{{Lang::get('lang.departments')}}</h1>
@stop
<!-- /header -->
<!-- breadcrumbs -->
@section('breadcrumbs')
<ol class="breadcrumb">

</ol>
@stop
<!-- /breadcrumbs -->
<!-- content -->
@section('content')
<!-- open a form -->
{!! Form::open(array('action' => 'Admin\helpdesk\DepartmentController@store' , 'method' => 'post','id'=>'Form') )!!}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">{!! Lang::get('lang.create_a_department') !!}</h3>	
    </div>
    <div class="box-body">
        @if(Session::has('errors'))
        <?php //dd($errors); ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <b>Alert!</b>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <br/>
            @if($errors->first('name'))
            <li class="error-message-padding">{!! $errors->first('name', ':message') !!}</li>
            @endif
            @if($errors->first('account_status'))
            <li class="error-message-padding">{!! $errors->first('account_status', ':message') !!}</li>
            @endif
            @if($errors->first('sla'))
            <li class="error-message-padding">{!! $errors->first('sla', ':message') !!}</li>
            @endif
            @if($errors->first('manager'))
            <li class="error-message-padding">{!! $errors->first('manager', ':message') !!}</li>
            @endif
            @if($errors->first('outgoing_email'))
            <li class="error-message-padding">{!! $errors->first('outgoing_email', ':message') !!}</li>
            @endif
        </div>
        @endif
          <div class="row">
            <!-- name -->
            <div class="col-xs-4 form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                {!! Form::label('name',Lang::get('lang.name')) !!} <span class="text-red"> *</span>
                {!! Form::text('name',null,['class' => 'form-control']) !!}
            </div>
            <!-- account status -->
            <div class="col-xs-4 form-group {{ $errors->has('account_status') ? 'has-error' : '' }}">
                {!! Form::label('type',Lang::get('lang.type')) !!}
                <a href="#" data-toggle="tooltip" title="{!! Lang::get('tooltip.department-type') !!}"><i class="fa fa-question-circle" style="padding: 0px;"></i></a>
                <div class="row">
                    <div class="col-xs-6">
                        {!! Form::radio('type','1',true) !!} {{Lang::get('lang.public')}}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::radio('type','0',null) !!} {{Lang::get('lang.private')}}
                    </div>
                </div>
            </div>
            <!-- sla -->
            
            <!-- manager -->
            <div class="col-xs-4 form-group {{ $errors->has('manager') ? 'has-error' : '' }}">
                {!! Form::label('manager',Lang::get('lang.manager')) !!}
                <a href="#" data-toggle="tooltip" title="{!! Lang::get('tooltip.department-manager') !!}"><i class="fa fa-question-circle" style="padding: 0px;"></i></a>
                {!!Form::select('manager',[null=>Lang::get('lang.select_a_manager'),Lang::get('lang.manager')=>$user->pluck('full_name','id')->toArray()],null,['class' => 'form-control select']) !!}
            </div>
        </div>
    </div>
    <div class="box-header with-border">
        <h4 class="box-title">{!! Lang::get('lang.outgoing_email_settings') !!}</h4>
    </div>
    <div class="box-body">
        <div class="row">
            <!-- sla -->
            <div class="col-xs-6 form-group {{ $errors->has('outgoing_email') ? 'has-error' : '' }}">
                {!! Form::label('outgoing_email',Lang::get('lang.outgoing_email')) !!}
                <a href="#" data-toggle="tooltip" title="{!! Lang::get('tooltip.department-outgoin-mail') !!}"><i class="fa fa-question-circle" style="padding: 0px;"></i></a>
                {!!Form::select('outgoing_email', ['' => Lang::get('lang.system_default'), Lang::get('lang.emails')=>$emails->pluck('email_name','id')->toArray()],null,['class' => 'form-control select']) !!}
            </div>
        </div>
        <div>
            <h4>{!! Lang::get('lang.department_signature') !!}</h4>
        </div>
        <div class="">
            {!! Form::textarea('department_sign',null,['class' => 'form-control','size' => '30x5' ,'id'=>'ckeditor']) !!}
        </div>
        <div class="form-group">
            <input type="checkbox" name="sys_department"> {{ Lang::get('lang.make-default-department')}}&nbsp;<a href="#" data-toggle="tooltip" title="{!! Lang::get('tooltip.default-department') !!}"><i class="fa fa-question-circle" style="padding: 0px;"></i></a>
        </div>
    </div>
    <div class="box-footer">
<!--        {!! Form::submit(Lang::get('lang.create'),['class'=>'form-group btn btn-primary'])!!}    -->
<!--        {!!Form::button('<i class="fa fa-floppy-o" aria-hidden="true">&nbsp;&nbsp;</i>'.Lang::get('lang.save'),['type' => 'submit', 'class' =>'btn btn-primary'])!!}-->
            <button type="submit" id="submit" class="btn btn-primary" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'>&nbsp;</i> Saving..."><i class="fa fa-floppy-o">&nbsp;&nbsp;</i>{!!Lang::get('lang.save')!!}</button>
    </div>
    {!!Form::close()!!}
</div>
@stop

resources/views/themes/default1/admin/helpdesk/agent/departments/index.blade.php
@extends('themes.default1.admin.layout.admin')

@section('Staffs')
active
@stop

@section('staffs-bar')
active
@stop

@section('departments')
class="active"
@stop

@section('HeadInclude')
@stop
<!-- header -->
@section('PageHeader')
<h1>{{Lang::get('lang.departments')}}</h1>
@stop
<!-- /header -->
<!-- breadcrumbs -->
@section('breadcrumbs')
<ol class="breadcrumb">

</ol>
@stop
<!-- /breadcrumbs -->
<!-- content -->
@section('content')
<div class="box box-primary">
    <div class="box-header">
        <h2 class="box-title">{!! Lang::get('lang.list_of_departments') !!}</h2><a href="{{route('departments.create')}}" class="btn btn-primary pull-right"><span class="glyphicon glyphicon-plus"></span> &nbsp;{{Lang::get('lang.create_a_department')}}</a></div>
    <div class="box-body">
        <!-- check whether success or not -->
        @if(Session::has('success'))
        <div class="alert alert-success alert-dismissable">
            <i class="fa  fa-check-circle"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {!! Session::get('success') !!}
        </div>
        @endif
        <!-- failure message -->
        @if(Session::has('fails'))
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <b>{!! Lang::get('lang.fails') !!}!</b>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {!! Session::get('fails') !!}
        </div>
        @endif
        <!-- table -->
           {!!$table->render('vendor.Chumper.template')!!}
    </div>
</div>
{!! $table->script('vendor.Chumper.department-table') !!}
@stop